version: '3.1'

services:

  webserver:
    image: webdevops/php-nginx:7.3
    ports:
      - 8080:80
    volumes:
      - ./src:/home/simple-currency-storage
    environment:
      WEB_DOCUMENT_ROOT: /home/simple-currency-storage/app
    links:
      - db
    depends_on: 
      - db

  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: currency
    ports:
      - 3306:3306
    volumes:
      - ./src/db.sql:/docker-entrypoint-initdb.d/db.sql:ro # executes the SQL script on the initialization
    command: mysqld --default-authentication-plugin=mysql_native_password # required since MySQL 8